### ISSUE TITLE
Not connecting

### ISSUE THREAD

**Issue by pankajxhtmljunkies** [opentok/presencekit-php#10]
Hi,

I am not able to connect the user list after entering the name. I have configured as per read me file.

See attached screenshot which continuously goes to connecting...

Please help me.

Thanks,
Pankaj
![error](https://cloud.githubusercontent.com/assets/6701775/7135786/c6637ebc-e2c7-11e4-826c-cab5fd1cc11a.png)

**Comment by aoberoi** [comment]
Hi @pankajxhtmljunkies 

Can you show us the entire output on the console? your screenshot just shows the first line in the JSON response of one request, there should be plenty of other activity.

**Comment by pankajxhtmljunkies** [comment]
Hi,

Thanks for reply.

![consolelog](https://cloud.githubusercontent.com/assets/6701775/7195728/5a52a53c-e4e2-11e4-84c6-883832d13b06.png)

**Comment by pankajxhtmljunkies** [comment]
Can you please help me to fix issue?

**Comment by aoberoi** [comment]
Hi @pankajxhtmljunkies, sorry for the extremely late reply.

implementing text chat is just about using the signaling API. i recommend checking out the tutorial and given code inside the Learning OpenTok tutorial here: https://github.com/opentok/learning-opentok-web#using-the-signaling-api-to-implement-text-chat. Also, there is a prebuilt text chat widget you can use here: https://github.com/opentok/text-chat
